-- categories
CREATE TABLE IF NOT EXISTS public.categories
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

-- users
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255),
    name varchar(255),
    password varchar(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- addresses
CREATE TABLE IF NOT EXISTS public.addresses
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city varchar(255),
    state varchar(255),
    street varchar(255),
    zip varchar(255),
    user_id bigint,
    CONSTRAINT addresses_pkey PRIMARY KEY (id),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
);

-- profiles
CREATE TABLE IF NOT EXISTS public.profiles
(
    id bigint NOT NULL,
    bio varchar(255),
    date_of_birth date,
    loyalty_points integer,
    phone_number varchar(255),
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_profiles_user FOREIGN KEY (id)
        REFERENCES public.users (id)
);

-- products
CREATE TABLE IF NOT EXISTS public.products
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255),
    name varchar(255),
    price numeric(38,2),
    category_id smallint,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id)
        REFERENCES public.categories (id)
);

-- wishlist (junction table)
CREATE TABLE IF NOT EXISTS public.wishlist
(
    user_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT wishlist_pkey PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id)
        REFERENCES public.users (id),
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id)
        REFERENCES public.products (id)
);
